module.exports = {
    tv: {display_name: 'TV',
        icon: '../images/tv.png',
        tap: 'watch_tv_on',
        taphold: 'watch_tv_off',
        stop: 'tv_stopir',
        swipeleft: 'tv_left',
        swiperight: 'tv_right',
        swipeup: 'tv_up',
        swipedown: 'tv_down',
        area11_tap_label: 'Back',
        area11_taphold_label: 'Exit',
        area11_tap: 'tv_back',
        area11_taphold: 'tv_exit',
        area12_tap_label: 'Volume +',
        area12_taphold_label: '',
        area12_tap: 'tv_volup',
        area12_taphold: '',
        area13_tap_label: 'Menu',
        area13_taphold_label: 'More...',
        area13_tap: 'tv_menu',
        area13_taphold: '',
        area21_tap_label: 'Channel-',
        area21_taphold_label: 'EPG',
        area21_tap: 'tv_channeldown',
        area21_taphold: 'tv_epg',
        area22_tap_label: 'OK',
        area22_taphold_label: '',
        area22_tap: 'tv_ok',
        area22_taphold: '#devices',
        area23_tap_label: 'Channel+',
        area23_taphold_label: '',
        area23_tap: 'tv_channelup',
        area23_taphold: '',
        area31_tap_label: 'Input',
        area31_taphold_label: 'Mute',
        area31_tap: 'tv_input',
        area31_taphold: 'tv_mute',
        area32_tap_label: 'Volume -',
        area32_taphold_label: '',
        area32_tap: 'tv_voldown',
        area32_taphold: '',
        area33_tap_label: 'ON',
        area33_taphold_label: 'OFF',
        area33_tap: 'watch_tv_on',
        area33_taphold: 'watch_tv_off'
    },
    /*net : { display_name: 'NET',
     icon: '../images/tv.png',
     tap: 'watch_tv_on',
     taphold: 'watch_tv_off',
     swipeleft: 'stb_left',
     swiperight: 'stb_right',
     swipeup: 'stb_up',
     swipedown: 'stb_down',
     area11_tap_label: 'Back',
     area11_taphold_label: 'Exit',
     area11_tap: 'stb_back',
     area11_taphold: 'stb_exit',
     area12_tap_label: 'Volume +',
     area12_taphold_label: '',
     area12_tap: 'stb_volup',
     area12_taphold: '',
     area13_tap_label: 'ON',
     area13_taphold_label: 'OFF',
     area13_tap: 'watch_tv_on',
     area13_taphold: 'watch_tv_off',
     area21_tap_label: 'Channel-',
     area21_taphold_label: 'EPG',
     area21_tap: 'stb_channeldown',
     area21_taphold: 'stb_epg',
     area22_tap_label: 'OK',
     area22_taphold_label: 'Info',
     area22_tap: 'stb_ok',
     area22_taphold: 'stb_info',
     area23_tap_label: 'Channel+',
     area23_taphold_label: 'Channels',
     area23_tap: 'stb_channelup',
     area23_taphold: 'stb_channels',
     area31_tap_label: 'VOD',
     area31_taphold_label: 'Music',
     area31_tap: 'stb_vod',
     area31_taphold: 'stb_music',
     area32_tap_label: 'Volume -',
     area32_taphold_label: '',
     area32_tap: 'stb_voldown',
     area32_taphold: '',
     area33_tap_label: 'Audio',
     area33_taphold_label: 'Subtitle',
     area33_tap: 'stb_audio',
     area33_taphold: 'stb_subtitle'
     },
     music: { 'display_name': 'Music',
     'icon': '../images/music.png',
     'tap': 'listen_music_on',
     'taphold': 'listen_music_off',
     'swipeleft': 'stb_left',
     'swiperight': 'stb_right',
     'swipeup': 'stb_up',
     'swipedown': 'stb_down',
     'area11_tap': 'stb_back',
     'area11_taphold': 'stb_exit',
     'area12_tap': 'stb_volup',
     'area12_taphold': 'stb_exit',
     'area13_tap': 'stb_vod',
     'area13_taphold': 'stb_music',
     'area21_tap': 'stb_channeldown',
     'area21_taphold': 'stb_epg',
     'area22_tap': 'stb_ok',
     'area22_taphold': 'stb_info',
     'area23_tap': 'stb_channelup',
     'area23_taphold': 'stb_channels',
     'area31_tap': 'stb_audio',
     'area31_taphold': '',
     'area32_tap': 'stb_voldown',
     'area32_taphold': '',
     'area33_tap': 'stb_subtitle',
     'area33_taphold': ''
     },*/
    atv: {'display_name': 'Apple TV',
        icon: '../images/atv.png',
        stop: 'tv_stopir',
        tap: 'watch_atv_on',
        taphold: 'watch_atv_off',
        swipeleft: 'atv_left',
        swiperight: 'atv_right',
        swipeup: 'atv_up',
        swipedown: 'atv_down',
        area11_tap_label: 'Back',
        area11_taphold_label: '',
        area11_tap: 'atv_menu',
        area11_taphold: '',
        area12_tap_label: 'Volume +',
        area12_taphold_label: '',
        area12_tap: 'tv_volup',
        area12_taphold: '',
        area13_tap_label: 'Menu',
        area13_taphold_label: '',
        area13_tap: 'atv_menu',
        area13_taphold: '',
        area21_tap_label: '',
        area21_taphold_label: 'Apple Remote',
        area21_tap: '',
        area21_taphold: 'remote://',
        area22_tap_label: 'OK',
        area22_taphold_label: '',
        area22_tap: 'atv_ok',
        area22_taphold: '#devices',
        area23_tap_label: 'Play/Pause',
        area23_taphold_label: '',
        area23_tap: 'atv_play',
        area23_taphold: '',
        area31_tap_label: '',
        area31_taphold_label: 'Mute',
        area31_tap: '',
        area31_taphold: 'tv_mute',
        area32_tap_label: 'Volume -',
        area32_taphold_label: '',
        area32_tap: 'tv_voldown',
        area32_taphold: '',
        area33_tap_label: 'ON',
        area33_taphold_label: 'OFF',
        area33_tap: 'watch_atv_on',
        area33_taphold: 'watch_atv_off'
    },
    ps3: {display_name: 'PS3',
        icon: '../images/ps3.png',
        stop: 'tv_stopir',
        tap: 'watch_ps3_on',
        taphold: 'watch_ps3_off',
        swipeleft: 'ps3_left',
        swiperight: 'ps3_right',
        swipeup: 'ps3_up',
        swipedown: 'ps3_down',
        area11_tap_label: 'Back',
        area11_taphold_label: 'ON',
        area11_tap: 'ps3_circle',
        area11_taphold: 'watch_ps3_on',
        area12_tap_label: 'Volume +',
        area12_taphold_label: 'Select',
        area12_tap: 'tv_volup',
        area12_taphold: 'ps3_select',
        area13_tap_label: 'Menu',
        area13_taphold_label: '',
        area13_tap: 'ps3_menu',
        area13_taphold: '',
        area21_tap_label: 'View',
        area21_taphold_label: 'Options',
        area21_tap: 'ps3_square',
        area21_taphold: 'ps3_triangle',
        area22_tap_label: 'OK',
        area22_taphold_label: '',
        area22_tap: 'ps3_ok',
        area22_taphold: '#devices',
        area23_tap_label: 'Play/Pause',
        area23_taphold_label: 'Stop',
        area23_tap: 'ps3_play',
        area23_taphold: 'ps3_stop',
        area31_tap_label: 'Previous',
        area31_taphold_label: '<< Scan',
        area31_tap: 'ps3_previous',
        area31_taphold: 'ps3_scanback',
        area32_tap_label: 'Volume -',
        area32_taphold_label: 'Mute',
        area32_tap: 'tv_voldown',
        area32_taphold: 'tv_mute',
        area33_tap_label: 'Next',
        area33_taphold_label: 'Scan >>',
        area33_tap: 'ps3_next',
        area33_taphold: 'ps3_scanforward'
    },
    home: {display_name: 'Home',
        icon: '../images/home.png',
        stop: 'tv_stopir',
        tap: '',
        taphold: '',
        swipeleft: '',
        swiperight: '',
        swipeup: '',
        swipedown: '',
        area11_tap_label: '',
        area11_taphold_label: '',
        area11_tap: '',
        area11_taphold: '',
        area12_tap_label: 'Garage',
        area12_taphold_label: '',
        area12_tap: 'garage_open',
        area12_taphold: '',
        area13_tap_label: '',
        area13_taphold_label: '',
        area13_tap: '',
        area13_taphold: '',
        area21_tap_label: '',
        area21_taphold_label: '',
        area21_tap: '',
        area21_taphold: '',
        area22_tap_label: '',
        area22_taphold_label: '',
        area22_tap: '',
        area22_taphold: '#devices',
        area23_tap_label: '',
        area23_taphold_label: '',
        area23_tap: '',
        area23_taphold: '',
        area31_tap_label: 'Bedroom...',
        area31_taphold_label: '',
        area31_tap: '#bedroom',
        area31_taphold: '',
        area32_tap_label: '',
        area32_taphold_label: '',
        area32_tap: '',
        area32_taphold: '',
        area33_tap_label: '',
        area33_taphold_label: '',
        area33_tap: '',
        area33_taphold: ''
    },
    bedroom: {display_name: 'Bedroom',
        icon: '../images/home.png',
        show_in_device_list: false,
        stop: 'tv_stopir',
        tap: '',
        taphold: '',
        swipeleft: '',
        swiperight: '',
        swipeup: '',
        swipedown: '',
        area11_tap_label: '<< Back',
        area11_taphold_label: '',
        area11_tap: '#home',
        area11_taphold: '',
        area12_tap_label: 'Lamp 1 ON',
        area12_taphold_label: 'Lamp 1 OFF',
        area12_tap: '',
        area12_taphold: '',
        area13_tap_label: 'Lamp 2 ON',
        area13_taphold_label: 'Lamp 2 OFF',
        area13_tap: '',
        area13_taphold: '',
        area21_tap_label: '',
        area21_taphold_label: '',
        area21_tap: '',
        area21_taphold: '',
        area22_tap_label: '',
        area22_taphold_label: '',
        area22_tap: '',
        area22_taphold: '#devices',
        area23_tap_label: '',
        area23_taphold_label: '',
        area23_tap: '',
        area23_taphold: '',
        area31_tap_label: '',
        area31_taphold_label: '',
        area31_tap: '',
        area31_taphold: '',
        area32_tap_label: '',
        area32_taphold_label: '',
        area32_tap: '',
        area32_taphold: '',
        area33_tap_label: '',
        area33_taphold_label: '',
        area33_tap: '',
        area33_taphold: ''
    },
    roomba: {display_name: 'Roomba',
        icon: '../images/roomba.png',
        show_in_device_list: true,
        stop: 'tv_stopir',
        tap: '',
        taphold: '',
        swipeleft: '',
        swiperight: '',
        swipeup: '',
        swipedown: '',
        area11_tap_label: '',
        area11_taphold_label: '',
        area11_tap: '',
        area11_taphold: '',
        area12_tap_label: 'Up',
        area12_taphold_label: '',
        area12_tap: 'roomba_up',
        area12_taphold: '',
        area13_tap_label: '',
        area13_taphold_label: '',
        area13_tap: '',
        area13_taphold: '',
        area21_tap_label: 'Left',
        area21_taphold_label: '',
        area21_tap: 'roomba_left',
        area21_taphold: '',
        area22_tap_label: 'Clean',
        area22_taphold_label: '',
        area22_tap: 'roomba_clean',
        area22_taphold: '#devices',
        area23_tap_label: 'Right',
        area23_taphold_label: '',
        area23_tap: 'roomba_right',
        area23_taphold: '',
        area31_tap_label: '',
        area31_taphold_label: '',
        area31_tap: '',
        area31_taphold: '',
        area32_tap_label: 'Dock',
        area32_taphold_label: '',
        area32_tap: 'roomba_dock',
        area32_taphold: '',
        area33_tap_label: '',
        area33_taphold_label: '',
        area33_tap: '',
        area33_taphold: ''
    }
}

